[package]
edition = "2021"
name = "rust_http_parser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "get"
path = "examples/get.rs"
[[example]]
name = "post"
path = "examples/post.rs"
